CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS produtos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    condicao VARCHAR(50) NOT NULL,
    modelo VARCHAR(255) NOT NULL,
    linha_numero INT UNSIGNED NOT NULL,
    armazenamento VARCHAR(100) NOT NULL,
    preco DECIMAL(10,2) NOT NULL,
    detalhes VARCHAR(255) NULL,
    foto_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE produtos ADD COLUMN linha_numero INT UNSIGNED NOT NULL DEFAULT 0 AFTER modelo;
